create table cms_category
(
    id                  varchar(64)             not null comment '编号'
        primary key,
    parent_id           varchar(64)             not null comment '父级编号',
    parent_ids          varchar(2000)           not null comment '所有父级编号',
    site_id             varchar(64) default '1' null comment '站点编号',
    office_id           varchar(64)             null comment '归属机构',
    module              varchar(20)             null comment '栏目模块',
    name                varchar(100)            not null comment '栏目名称',
    image               varchar(255)            null comment '栏目图片',
    href                varchar(255)            null comment '链接',
    target              varchar(20)             null comment '目标',
    description         varchar(255)            null comment '描述',
    keywords            varchar(255)            null comment '关键字',
    sort                int         default 30  null comment '排序（升序）',
    in_menu             char        default '1' null comment '是否在导航中显示',
    in_list             char        default '1' null comment '是否在分类页中显示列表',
    show_modes          char        default '0' null comment '展现方式',
    allow_comment       char                    null comment '是否允许评论',
    is_audit            char                    null comment '是否需要审核',
    custom_list_view    varchar(255)            null comment '自定义列表视图',
    custom_content_view varchar(255)            null comment '自定义内容视图',
    view_config         text                    null comment '视图配置',
    create_by           varchar(64)             null comment '创建者',
    create_date         datetime                null comment '创建时间',
    update_by           varchar(64)             null comment '更新者',
    update_date         datetime                null comment '更新时间',
    remarks             varchar(255)            null comment '备注信息',
    del_flag            char        default '0' not null comment '删除标记'
)
    comment '栏目表' charset = utf8;

create index cms_category_del_flag
    on cms_category (del_flag);

create index cms_category_module
    on cms_category (module);

create index cms_category_name
    on cms_category (name);

create index cms_category_office_id
    on cms_category (office_id);

create index cms_category_parent_id
    on cms_category (parent_id);

create index cms_category_site_id
    on cms_category (site_id);

create index cms_category_sort
    on cms_category (sort);

INSERT INTO jeesite.cms_category (id, parent_id, parent_ids, site_id, office_id, module, name, image, href, target, description, keywords, sort, in_menu, in_list, show_modes, allow_comment, is_audit, custom_list_view, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('1', '0', '0,', '0', '1', null, '顶级栏目', null, null, null, null, null, 0, '1', '1', '0', '0', '1', null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '0');
INSERT INTO jeesite.cms_category (id, parent_id, parent_ids, site_id, office_id, module, name, image, href, target, description, keywords, sort, in_menu, in_list, show_modes, allow_comment, is_audit, custom_list_view, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('10', '1', '0,1,', '1', '4', 'article', '软件介绍', null, null, null, null, null, 20, '1', '1', '0', '1', '0', null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '1');
INSERT INTO jeesite.cms_category (id, parent_id, parent_ids, site_id, office_id, module, name, image, href, target, description, keywords, sort, in_menu, in_list, show_modes, allow_comment, is_audit, custom_list_view, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('11', '10', '0,1,10,', '1', '4', 'article', '网络工具', null, null, null, null, null, 30, '1', '1', '0', '1', '0', null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '1');
INSERT INTO jeesite.cms_category (id, parent_id, parent_ids, site_id, office_id, module, name, image, href, target, description, keywords, sort, in_menu, in_list, show_modes, allow_comment, is_audit, custom_list_view, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('12', '10', '0,1,10,', '1', '4', 'article', '浏览工具', null, null, null, null, null, 40, '1', '1', '0', '1', '0', null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '1');
INSERT INTO jeesite.cms_category (id, parent_id, parent_ids, site_id, office_id, module, name, image, href, target, description, keywords, sort, in_menu, in_list, show_modes, allow_comment, is_audit, custom_list_view, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('13', '10', '0,1,10,', '1', '4', 'article', '浏览辅助', null, null, null, null, null, 50, '1', '1', '0', '1', '0', null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '1');
INSERT INTO jeesite.cms_category (id, parent_id, parent_ids, site_id, office_id, module, name, image, href, target, description, keywords, sort, in_menu, in_list, show_modes, allow_comment, is_audit, custom_list_view, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('14', '10', '0,1,10,', '1', '4', 'article', '网络优化', null, null, null, null, null, 50, '1', '1', '0', '1', '0', null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '1');
INSERT INTO jeesite.cms_category (id, parent_id, parent_ids, site_id, office_id, module, name, image, href, target, description, keywords, sort, in_menu, in_list, show_modes, allow_comment, is_audit, custom_list_view, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('15', '10', '0,1,10,', '1', '4', 'article', '邮件处理', null, null, null, null, null, 50, '1', '1', '0', '1', '0', null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '1');
INSERT INTO jeesite.cms_category (id, parent_id, parent_ids, site_id, office_id, module, name, image, href, target, description, keywords, sort, in_menu, in_list, show_modes, allow_comment, is_audit, custom_list_view, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('16', '10', '0,1,10,', '1', '4', 'article', '下载工具', null, null, null, null, null, 50, '1', '1', '0', '1', '0', null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '1');
INSERT INTO jeesite.cms_category (id, parent_id, parent_ids, site_id, office_id, module, name, image, href, target, description, keywords, sort, in_menu, in_list, show_modes, allow_comment, is_audit, custom_list_view, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('17', '10', '0,1,10,', '1', '4', 'article', '搜索工具', null, null, null, null, null, 50, '1', '1', '2', '1', '0', null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '1');
INSERT INTO jeesite.cms_category (id, parent_id, parent_ids, site_id, office_id, module, name, image, href, target, description, keywords, sort, in_menu, in_list, show_modes, allow_comment, is_audit, custom_list_view, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('18', '1', '0,1,', '1', '5', 'link', '友情链接', null, null, null, null, null, 90, '1', '1', '0', '1', '0', null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '1');
INSERT INTO jeesite.cms_category (id, parent_id, parent_ids, site_id, office_id, module, name, image, href, target, description, keywords, sort, in_menu, in_list, show_modes, allow_comment, is_audit, custom_list_view, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('19', '18', '0,1,18,', '1', '5', 'link', '常用网站', null, null, null, null, null, 50, '1', '1', '0', '1', '0', null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '1');
INSERT INTO jeesite.cms_category (id, parent_id, parent_ids, site_id, office_id, module, name, image, href, target, description, keywords, sort, in_menu, in_list, show_modes, allow_comment, is_audit, custom_list_view, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('2', '1', '0,1,', '1', '3', 'article', '组织机构', null, null, null, null, null, 10, '1', '1', '0', '0', '1', null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '1');
INSERT INTO jeesite.cms_category (id, parent_id, parent_ids, site_id, office_id, module, name, image, href, target, description, keywords, sort, in_menu, in_list, show_modes, allow_comment, is_audit, custom_list_view, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('20', '18', '0,1,18,', '1', '5', 'link', '门户网站', null, null, null, null, null, 50, '1', '1', '0', '1', '0', null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '1');
INSERT INTO jeesite.cms_category (id, parent_id, parent_ids, site_id, office_id, module, name, image, href, target, description, keywords, sort, in_menu, in_list, show_modes, allow_comment, is_audit, custom_list_view, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('21', '18', '0,1,18,', '1', '5', 'link', '购物网站', null, null, null, null, null, 50, '1', '1', '0', '1', '0', null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '1');
INSERT INTO jeesite.cms_category (id, parent_id, parent_ids, site_id, office_id, module, name, image, href, target, description, keywords, sort, in_menu, in_list, show_modes, allow_comment, is_audit, custom_list_view, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('22', '18', '0,1,18,', '1', '5', 'link', '交友社区', null, null, null, null, null, 50, '1', '1', '0', '1', '0', null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '1');
INSERT INTO jeesite.cms_category (id, parent_id, parent_ids, site_id, office_id, module, name, image, href, target, description, keywords, sort, in_menu, in_list, show_modes, allow_comment, is_audit, custom_list_view, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('23', '18', '0,1,18,', '1', '5', 'link', '音乐视频', null, null, null, null, null, 50, '1', '1', '0', '1', '0', null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '1');
INSERT INTO jeesite.cms_category (id, parent_id, parent_ids, site_id, office_id, module, name, image, href, target, description, keywords, sort, in_menu, in_list, show_modes, allow_comment, is_audit, custom_list_view, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('24', '1', '0,1,', '1', '6', null, '百度一下', null, 'http://www.baidu.com', '_blank', null, null, 90, '1', '1', '0', '1', '0', null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '1');
INSERT INTO jeesite.cms_category (id, parent_id, parent_ids, site_id, office_id, module, name, image, href, target, description, keywords, sort, in_menu, in_list, show_modes, allow_comment, is_audit, custom_list_view, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('25', '1', '0,1,', '1', '6', null, '全文检索', null, '/search', null, null, null, 90, '0', '1', '0', '1', '0', null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '1');
INSERT INTO jeesite.cms_category (id, parent_id, parent_ids, site_id, office_id, module, name, image, href, target, description, keywords, sort, in_menu, in_list, show_modes, allow_comment, is_audit, custom_list_view, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('26', '1', '0,1,', '2', '6', 'article', '测试栏目', null, null, null, null, null, 90, '1', '1', '0', '1', '0', null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '0');
INSERT INTO jeesite.cms_category (id, parent_id, parent_ids, site_id, office_id, module, name, image, href, target, description, keywords, sort, in_menu, in_list, show_modes, allow_comment, is_audit, custom_list_view, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('27', '1', '0,1,', '1', '6', null, '公共留言', null, '/guestbook', null, null, null, 90, '1', '1', '0', '1', '0', null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '1');
INSERT INTO jeesite.cms_category (id, parent_id, parent_ids, site_id, office_id, module, name, image, href, target, description, keywords, sort, in_menu, in_list, show_modes, allow_comment, is_audit, custom_list_view, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('3', '2', '0,1,2,', '1', '3', 'article', '网站简介', null, null, null, null, null, 30, '1', '1', '0', '0', '1', null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '1');
INSERT INTO jeesite.cms_category (id, parent_id, parent_ids, site_id, office_id, module, name, image, href, target, description, keywords, sort, in_menu, in_list, show_modes, allow_comment, is_audit, custom_list_view, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('4', '2', '0,1,2,', '1', '3', 'article', '内部机构', null, null, null, null, null, 40, '1', '1', '0', '0', '1', null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '1');
INSERT INTO jeesite.cms_category (id, parent_id, parent_ids, site_id, office_id, module, name, image, href, target, description, keywords, sort, in_menu, in_list, show_modes, allow_comment, is_audit, custom_list_view, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('5', '2', '0,1,2,', '1', '3', 'article', '地方机构', null, null, null, null, null, 50, '1', '1', '0', '0', '1', null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '1');
INSERT INTO jeesite.cms_category (id, parent_id, parent_ids, site_id, office_id, module, name, image, href, target, description, keywords, sort, in_menu, in_list, show_modes, allow_comment, is_audit, custom_list_view, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('6', '1', '0,1,', '1', '3', 'article', '质量检验', null, null, null, null, null, 20, '1', '1', '1', '1', '0', null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '1');
INSERT INTO jeesite.cms_category (id, parent_id, parent_ids, site_id, office_id, module, name, image, href, target, description, keywords, sort, in_menu, in_list, show_modes, allow_comment, is_audit, custom_list_view, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('7', '6', '0,1,6,', '1', '3', 'article', '产品质量', null, null, null, null, null, 30, '1', '1', '0', '1', '0', null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '1');
INSERT INTO jeesite.cms_category (id, parent_id, parent_ids, site_id, office_id, module, name, image, href, target, description, keywords, sort, in_menu, in_list, show_modes, allow_comment, is_audit, custom_list_view, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('8', '6', '0,1,6,', '1', '3', 'article', '技术质量', null, null, null, null, null, 40, '1', '1', '0', '1', '0', null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '1');
INSERT INTO jeesite.cms_category (id, parent_id, parent_ids, site_id, office_id, module, name, image, href, target, description, keywords, sort, in_menu, in_list, show_modes, allow_comment, is_audit, custom_list_view, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('9', '6', '0,1,6,', '1', '3', 'article', '工程质量', null, null, null, null, null, 50, '1', '1', '0', '1', '0', null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '1');
INSERT INTO jeesite.cms_category (id, parent_id, parent_ids, site_id, office_id, module, name, image, href, target, description, keywords, sort, in_menu, in_list, show_modes, allow_comment, is_audit, custom_list_view, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('da45061115104f64a4eb3548d831b2c4', '1', '0,1,', '1', '1', 'article', '测试', '', '', '', '', '', 30, '0', '0', '0', '0', '0', '', '', '', '1', '2020-04-20 16:18:59', '1', '2020-04-20 16:20:45', null, '0');