create table cms_article
(
    id                  varchar(64)      not null comment '编号'
        primary key,
    category_id         varchar(64)      not null comment '栏目编号',
    title               varchar(255)     not null comment '标题',
    link                varchar(255)     null comment '文章链接',
    color               varchar(50)      null comment '标题颜色',
    image               varchar(255)     null comment '文章图片',
    keywords            varchar(255)     null comment '关键字',
    description         varchar(255)     null comment '描述、摘要',
    weight              int  default 0   null comment '权重，越大越靠前',
    weight_date         datetime         null comment '权重期限',
    hits                int  default 0   null comment '点击数',
    posid               varchar(10)      null comment '推荐位，多选',
    custom_content_view varchar(255)     null comment '自定义内容视图',
    view_config         text             null comment '视图配置',
    create_by           varchar(64)      null comment '创建者',
    create_date         datetime         null comment '创建时间',
    update_by           varchar(64)      null comment '更新者',
    update_date         datetime         null comment '更新时间',
    remarks             varchar(255)     null comment '备注信息',
    del_flag            char default '0' not null comment '删除标记'
)
    comment '文章表' charset = utf8;

create index cms_article_category_id
    on cms_article (category_id);

create index cms_article_create_by
    on cms_article (create_by);

create index cms_article_del_flag
    on cms_article (del_flag);

create index cms_article_keywords
    on cms_article (keywords);

create index cms_article_title
    on cms_article (title);

create index cms_article_update_date
    on cms_article (update_date);

create index cms_article_weight
    on cms_article (weight);

INSERT INTO jeesite.cms_article (id, category_id, title, link, color, image, keywords, description, weight, weight_date, hits, posid, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('1', '3', '文章标题标题标题标题', null, 'green', null, '关键字1,关键字2', null, 0, null, 0, null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '0');
INSERT INTO jeesite.cms_article (id, category_id, title, link, color, image, keywords, description, weight, weight_date, hits, posid, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('10', '4', '文章标题标题标题标题', null, null, null, '关键字1,关键字2', null, 0, null, 0, null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '0');
INSERT INTO jeesite.cms_article (id, category_id, title, link, color, image, keywords, description, weight, weight_date, hits, posid, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('11', '5', '文章标题标题标题标题', null, null, null, '关键字1,关键字2', null, 0, null, 0, null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '0');
INSERT INTO jeesite.cms_article (id, category_id, title, link, color, image, keywords, description, weight, weight_date, hits, posid, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('12', '5', '文章标题标题标题标题', null, null, null, '关键字1,关键字2', null, 0, null, 0, null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '0');
INSERT INTO jeesite.cms_article (id, category_id, title, link, color, image, keywords, description, weight, weight_date, hits, posid, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('13', '5', '文章标题标题标题标题', null, null, null, '关键字1,关键字2', null, 0, null, 0, null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '0');
INSERT INTO jeesite.cms_article (id, category_id, title, link, color, image, keywords, description, weight, weight_date, hits, posid, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('14', '7', '文章标题标题标题标题', null, null, null, '关键字1,关键字2', null, 0, null, 1, null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '0');
INSERT INTO jeesite.cms_article (id, category_id, title, link, color, image, keywords, description, weight, weight_date, hits, posid, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('15', '7', '文章标题标题标题标题', null, null, null, '关键字1,关键字2', null, 0, null, 0, null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '0');
INSERT INTO jeesite.cms_article (id, category_id, title, link, color, image, keywords, description, weight, weight_date, hits, posid, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('16', '7', '文章标题标题标题标题', null, null, null, '关键字1,关键字2', null, 0, null, 0, null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '0');
INSERT INTO jeesite.cms_article (id, category_id, title, link, color, image, keywords, description, weight, weight_date, hits, posid, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('17', '7', '文章标题标题标题标题', null, null, null, '关键字1,关键字2', null, 0, null, 0, null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '0');
INSERT INTO jeesite.cms_article (id, category_id, title, link, color, image, keywords, description, weight, weight_date, hits, posid, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('18', '8', '文章标题标题标题标题', null, null, null, '关键字1,关键字2', null, 0, null, 0, null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '0');
INSERT INTO jeesite.cms_article (id, category_id, title, link, color, image, keywords, description, weight, weight_date, hits, posid, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('19', '8', '文章标题标题标题标题', null, null, null, '关键字1,关键字2', null, 0, null, 0, null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '0');
INSERT INTO jeesite.cms_article (id, category_id, title, link, color, image, keywords, description, weight, weight_date, hits, posid, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('2', '3', '文章标题标题标题标题', null, 'red', null, '关键字1,关键字2', null, 0, null, 0, null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '0');
INSERT INTO jeesite.cms_article (id, category_id, title, link, color, image, keywords, description, weight, weight_date, hits, posid, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('20', '8', '文章标题标题标题标题', null, null, null, '关键字1,关键字2', null, 0, null, 0, null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '0');
INSERT INTO jeesite.cms_article (id, category_id, title, link, color, image, keywords, description, weight, weight_date, hits, posid, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('21', '8', '文章标题标题标题标题', null, null, null, '关键字1,关键字2', null, 0, null, 0, null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '0');
INSERT INTO jeesite.cms_article (id, category_id, title, link, color, image, keywords, description, weight, weight_date, hits, posid, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('22', '9', '文章标题标题标题标题', null, null, null, '关键字1,关键字2', null, 0, null, 0, null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '0');
INSERT INTO jeesite.cms_article (id, category_id, title, link, color, image, keywords, description, weight, weight_date, hits, posid, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('23', '9', '文章标题标题标题标题', null, null, null, '关键字1,关键字2', null, 0, null, 0, null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '0');
INSERT INTO jeesite.cms_article (id, category_id, title, link, color, image, keywords, description, weight, weight_date, hits, posid, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('24', '9', '文章标题标题标题标题', null, null, null, '关键字1,关键字2', null, 0, null, 0, null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '0');
INSERT INTO jeesite.cms_article (id, category_id, title, link, color, image, keywords, description, weight, weight_date, hits, posid, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('25', '9', '文章标题标题标题标题', null, null, null, '关键字1,关键字2', null, 0, null, 0, null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '0');
INSERT INTO jeesite.cms_article (id, category_id, title, link, color, image, keywords, description, weight, weight_date, hits, posid, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('26', '9', '文章标题标题标题标题', null, null, null, '关键字1,关键字2', null, 0, null, 0, null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '0');
INSERT INTO jeesite.cms_article (id, category_id, title, link, color, image, keywords, description, weight, weight_date, hits, posid, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('27', '11', '文章标题标题标题标题', null, null, null, '关键字1,关键字2', null, 0, null, 0, null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '0');
INSERT INTO jeesite.cms_article (id, category_id, title, link, color, image, keywords, description, weight, weight_date, hits, posid, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('28', '11', '文章标题标题标题标题', null, null, null, '关键字1,关键字2', null, 0, null, 0, null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '0');
INSERT INTO jeesite.cms_article (id, category_id, title, link, color, image, keywords, description, weight, weight_date, hits, posid, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('29', '11', '文章标题标题标题标题', null, null, null, '关键字1,关键字2', null, 0, null, 0, null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '0');
INSERT INTO jeesite.cms_article (id, category_id, title, link, color, image, keywords, description, weight, weight_date, hits, posid, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('3', '3', '文章标题标题标题标题', null, null, null, '关键字1,关键字2', null, 0, null, 0, null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '0');
INSERT INTO jeesite.cms_article (id, category_id, title, link, color, image, keywords, description, weight, weight_date, hits, posid, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('30', '11', '文章标题标题标题标题', null, null, null, '关键字1,关键字2', null, 0, null, 0, null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '0');
INSERT INTO jeesite.cms_article (id, category_id, title, link, color, image, keywords, description, weight, weight_date, hits, posid, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('31', '11', '文章标题标题标题标题', null, null, null, '关键字1,关键字2', null, 0, null, 0, null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '0');
INSERT INTO jeesite.cms_article (id, category_id, title, link, color, image, keywords, description, weight, weight_date, hits, posid, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('32', '12', '文章标题标题标题标题', null, null, null, '关键字1,关键字2', null, 0, null, 0, null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '0');
INSERT INTO jeesite.cms_article (id, category_id, title, link, color, image, keywords, description, weight, weight_date, hits, posid, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('33', '12', '文章标题标题标题标题', null, null, null, '关键字1,关键字2', null, 0, null, 0, null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '0');
INSERT INTO jeesite.cms_article (id, category_id, title, link, color, image, keywords, description, weight, weight_date, hits, posid, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('34', '12', '文章标题标题标题标题', null, null, null, '关键字1,关键字2', null, 0, null, 0, null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '0');
INSERT INTO jeesite.cms_article (id, category_id, title, link, color, image, keywords, description, weight, weight_date, hits, posid, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('35', '12', '文章标题标题标题标题', null, null, null, '关键字1,关键字2', null, 0, null, 0, null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '0');
INSERT INTO jeesite.cms_article (id, category_id, title, link, color, image, keywords, description, weight, weight_date, hits, posid, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('36', '12', '文章标题标题标题标题', null, null, null, '关键字1,关键字2', null, 0, null, 0, null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '0');
INSERT INTO jeesite.cms_article (id, category_id, title, link, color, image, keywords, description, weight, weight_date, hits, posid, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('37', '13', '文章标题标题标题标题', null, null, null, '关键字1,关键字2', null, 0, null, 0, null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '0');
INSERT INTO jeesite.cms_article (id, category_id, title, link, color, image, keywords, description, weight, weight_date, hits, posid, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('38', '13', '文章标题标题标题标题', null, null, null, '关键字1,关键字2', null, 0, null, 0, null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '0');
INSERT INTO jeesite.cms_article (id, category_id, title, link, color, image, keywords, description, weight, weight_date, hits, posid, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('39', '13', '文章标题标题标题标题', null, null, null, '关键字1,关键字2', null, 0, null, 0, null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '0');
INSERT INTO jeesite.cms_article (id, category_id, title, link, color, image, keywords, description, weight, weight_date, hits, posid, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('4', '3', '文章标题标题标题标题', null, 'green', null, '关键字1,关键字2', null, 0, null, 0, null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '0');
INSERT INTO jeesite.cms_article (id, category_id, title, link, color, image, keywords, description, weight, weight_date, hits, posid, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('40', '13', '文章标题标题标题标题', null, null, null, '关键字1,关键字2', null, 0, null, 0, null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '0');
INSERT INTO jeesite.cms_article (id, category_id, title, link, color, image, keywords, description, weight, weight_date, hits, posid, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('41', '14', '文章标题标题标题标题', null, null, null, '关键字1,关键字2', null, 0, null, 0, null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '0');
INSERT INTO jeesite.cms_article (id, category_id, title, link, color, image, keywords, description, weight, weight_date, hits, posid, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('42', '14', '文章标题标题标题标题', null, null, null, '关键字1,关键字2', null, 0, null, 0, null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '0');
INSERT INTO jeesite.cms_article (id, category_id, title, link, color, image, keywords, description, weight, weight_date, hits, posid, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('43', '14', '文章标题标题标题标题', null, null, null, '关键字1,关键字2', null, 0, null, 0, null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '0');
INSERT INTO jeesite.cms_article (id, category_id, title, link, color, image, keywords, description, weight, weight_date, hits, posid, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('44', '14', '文章标题标题标题标题', null, null, null, '关键字1,关键字2', null, 0, null, 0, null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '0');
INSERT INTO jeesite.cms_article (id, category_id, title, link, color, image, keywords, description, weight, weight_date, hits, posid, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('45', '14', '文章标题标题标题标题', null, null, null, '关键字1,关键字2', null, 0, null, 0, null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '0');
INSERT INTO jeesite.cms_article (id, category_id, title, link, color, image, keywords, description, weight, weight_date, hits, posid, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('46', '15', '文章标题标题标题标题', null, null, null, '关键字1,关键字2', null, 0, null, 0, null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '0');
INSERT INTO jeesite.cms_article (id, category_id, title, link, color, image, keywords, description, weight, weight_date, hits, posid, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('47', '15', '文章标题标题标题标题', null, null, null, '关键字1,关键字2', null, 0, null, 0, null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '0');
INSERT INTO jeesite.cms_article (id, category_id, title, link, color, image, keywords, description, weight, weight_date, hits, posid, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('48', '15', '文章标题标题标题标题', null, null, null, '关键字1,关键字2', null, 0, null, 0, null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '0');
INSERT INTO jeesite.cms_article (id, category_id, title, link, color, image, keywords, description, weight, weight_date, hits, posid, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('49', '16', '文章标题标题标题标题', null, null, null, '关键字1,关键字2', null, 0, null, 0, null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '0');
INSERT INTO jeesite.cms_article (id, category_id, title, link, color, image, keywords, description, weight, weight_date, hits, posid, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('5', '3', '文章标题标题标题标题', null, null, null, '关键字1,关键字2', null, 0, null, 0, null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '0');
INSERT INTO jeesite.cms_article (id, category_id, title, link, color, image, keywords, description, weight, weight_date, hits, posid, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('50', '17', '文章标题标题标题标题', null, null, null, '关键字1,关键字2', null, 0, null, 0, null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '0');
INSERT INTO jeesite.cms_article (id, category_id, title, link, color, image, keywords, description, weight, weight_date, hits, posid, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('51', '17', '文章标题标题标题标题', null, null, null, '关键字1,关键字2', null, 0, null, 0, null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '0');
INSERT INTO jeesite.cms_article (id, category_id, title, link, color, image, keywords, description, weight, weight_date, hits, posid, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('52', '26', '文章标题标题标题标题', null, null, null, '关键字1,关键字2', null, 0, null, 0, null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '0');
INSERT INTO jeesite.cms_article (id, category_id, title, link, color, image, keywords, description, weight, weight_date, hits, posid, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('53', '26', '文章标题标题标题标题', null, null, null, '关键字1,关键字2', null, 0, null, 0, null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '0');
INSERT INTO jeesite.cms_article (id, category_id, title, link, color, image, keywords, description, weight, weight_date, hits, posid, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('6', '3', '文章标题标题标题标题', null, null, null, '关键字1,关键字2', null, 0, null, 0, null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '0');
INSERT INTO jeesite.cms_article (id, category_id, title, link, color, image, keywords, description, weight, weight_date, hits, posid, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('7', '4', '文章标题标题标题标题', null, null, null, '关键字1,关键字2', null, 0, null, 0, null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '0');
INSERT INTO jeesite.cms_article (id, category_id, title, link, color, image, keywords, description, weight, weight_date, hits, posid, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('8', '4', '文章标题标题标题标题', null, 'blue', null, '关键字1,关键字2', null, 0, null, 0, null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '0');
INSERT INTO jeesite.cms_article (id, category_id, title, link, color, image, keywords, description, weight, weight_date, hits, posid, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('898bd05bcfc342c5b24f404ed350981a', 'da45061115104f64a4eb3548d831b2c4', '565656755675675565656', '', '', '', '', '', 0, null, 7, ',null,', '', '', '1', '2020-04-20 16:22:28', '1', '2020-04-20 16:22:28', null, '0');
INSERT INTO jeesite.cms_article (id, category_id, title, link, color, image, keywords, description, weight, weight_date, hits, posid, custom_content_view, view_config, create_by, create_date, update_by, update_date, remarks, del_flag) VALUES ('9', '4', '文章标题标题标题标题', null, null, null, '关键字1,关键字2', null, 0, null, 0, null, null, null, '1', '2013-05-27 08:00:00', '1', '2013-05-27 08:00:00', null, '0');